#!/bin/bash

for tbl in `psql -U postgres -qAt -c "select tablename from pg_tables where schemaname = 'public';" $1` ; do
echo "# alter table: "$tbl;
psql -U postgres -c "alter table \"$tbl\" owner to $2" $1 ;
done

exit 0
