#!/bin/bash

database=$1
schema=$2
role=$3

for tbl in `psql -U postgres -qAt -c "select tablename from pg_tables where schemaname = '$schema';" $database` ; do
echo "# alter table: "$tbl;
psql -U postgres -c "alter table \"$schema\".\"$tbl\" owner to $role" $database ;
done

exit 0
