#!/bin/bash

database=$1
schema=$2
role=$3

for tbl in `psql -U postgres -qAt -c "select sequence_name from information_schema.sequences where sequence_schema = '$schema';" $database` ; do
psql -U postgres -c "alter table \"$schema\".\"$tbl\" owner to $role" $database ;
done

exit 0
