#!/bin/bash

for tbl in `psql -U postgres -qAt -c "select table_name from information_schema.views where table_schema = 'public';" $1` ; do
psql -U postgres -c "alter table \"$tbl\" owner to $2" $1 ;
done

exit 0
